#pragma once

#include <sasd/ui/geometry.hpp>

#include <cstdint>
#include <string>
#include <variant>

namespace sasd::ui {

struct QuitEvent {};

/**
 * Notification that a Widget gained or lost logical keyboard focus.
 *
 * FocusManager updates the widget's focus state before delivering this notification, so event
 * handlers can query Widget::hasFocus() and observe the new state. Focus notifications generated by
 * FocusManager are delivered directly to the affected widget and are not used as a veto mechanism.
 */
struct FocusEvent {
    bool gained{false};
};

enum class Key : std::uint16_t {
    unknown,
    enter,
    escape,
    tab,
    backspace,
    delete_forward,
    space,
    left,
    right,
    up,
    down,
    home,
    end,
    page_up,
    page_down,
};

enum class KeyModifier : std::uint8_t {
    none = 0,
    shift = 1U << 0U,
    control = 1U << 1U,
    alt = 1U << 2U,
    meta = 1U << 3U,
};

[[nodiscard]] constexpr KeyModifier operator|(KeyModifier left, KeyModifier right) noexcept {
    return static_cast<KeyModifier>(static_cast<std::uint8_t>(left) |
                                    static_cast<std::uint8_t>(right));
}

[[nodiscard]] constexpr bool hasModifier(KeyModifier value, KeyModifier modifier) noexcept {
    return (static_cast<std::uint8_t>(value) & static_cast<std::uint8_t>(modifier)) != 0U;
}

struct KeyEvent {
    Key key{Key::unknown};
    bool pressed{true};
    KeyModifier modifiers{KeyModifier::none};
};

/** Text input is separate from physical key input to support Unicode, IME and terminal backends. */
struct TextInputEvent {
    std::string text;
};

struct ResizeEvent {
    Size size{};
};

using Event = std::variant<QuitEvent, FocusEvent, KeyEvent, TextInputEvent, ResizeEvent>;

/**
 * Result returned by a widget after receiving one semantic event.
 *
 * ignored means that the widget deliberately leaves the event available for further routing.
 * handled stops propagation at that widget. Keeping this result explicit is preferable to a plain
 * bool because call sites remain readable when more routing behavior is added later.
 */
enum class EventResult : std::uint8_t {
    ignored,
    handled,
};

} // namespace sasd::ui
