#pragma once

#include <sasd/ui/geometry.hpp>

#include <cstdint>
#include <string>
#include <variant>

namespace sasd::ui {

struct QuitEvent {};

/**
 * Notification that a Widget gained or lost logical keyboard focus.
 *
 * FocusManager updates the widget's focus state before delivering this notification, so event
 * handlers can query Widget::hasFocus() and observe the new state. Focus notifications generated by
 * FocusManager are delivered directly to the affected widget and are not used as a veto mechanism.
 */
struct FocusEvent {
    bool gained{false};
};

enum class Key : std::uint16_t {
    unknown,
    enter,
    escape,
    tab,
    backspace,
    delete_forward,
    space,
    left,
    right,
    up,
    down,
    home,
    end,
    page_up,
    page_down,

    /*
     * Function-key identity is semantic and backend-neutral. Terminal backends map VT/ANSI escape
     * sequences here; later desktop backends can map their native key codes to the same values.
     */
    f1,
    f2,
    f3,
    f4,
    f5,
    f6,
    f7,
    f8,
    f9,
    f10,
    f11,
    f12,
};

enum class KeyModifier : std::uint8_t {
    none = 0,
    shift = 1U << 0U,
    control = 1U << 1U,
    alt = 1U << 2U,
    meta = 1U << 3U,
};

[[nodiscard]] constexpr KeyModifier operator|(KeyModifier left, KeyModifier right) noexcept {
    return static_cast<KeyModifier>(static_cast<std::uint8_t>(left) |
                                    static_cast<std::uint8_t>(right));
}

[[nodiscard]] constexpr bool hasModifier(KeyModifier value, KeyModifier modifier) noexcept {
    return (static_cast<std::uint8_t>(value) & static_cast<std::uint8_t>(modifier)) != 0U;
}

struct KeyEvent {
    Key key{Key::unknown};
    bool pressed{true};
    KeyModifier modifiers{KeyModifier::none};
};

/** Text input is separate from physical key input to support Unicode, IME and terminal backends. */
struct TextInputEvent {
    std::string text;
};

/**
 * Semantic pointer action independent of a concrete mouse/touch/pen API.
 *
 * M3 initially maps desktop mouse movement and button transitions. Wheel/gesture/composition-style
 * pointer data remains a later extension rather than being squeezed into an inaccurate first model.
 */
enum class PointerAction : std::uint8_t {
    move,
    press,
    release,
};

/**
 * Backend-neutral identity for the common desktop pointer buttons.
 *
 * "other" preserves the fact that a native button transition happened even when the platform offers
 * a button identity outside this initial portable set. "none" is used for pure movement.
 */
enum class PointerButton : std::uint8_t {
    none,
    primary,
    middle,
    secondary,
    auxiliary1,
    auxiliary2,
    other,
};

/**
 * Pointer input in logical UI coordinates.
 *
 * position uses the same logical coordinate space as top-level Widget layout, not physical device
 * pixels. Backend adapters are responsible for applying their DPI/logical-presentation transform
 * before constructing this event.
 *
 * click_count is meaningful for press/release events when the native backend can provide it; zero is
 * used for movement. Target selection is intentionally not embedded in the event and is handled by
 * HitTest plus the normal EventDispatcher routing boundary.
 */
struct PointerEvent {
    Point position{};
    PointerAction action{PointerAction::move};
    PointerButton button{PointerButton::none};
    std::uint8_t click_count{0};
};

struct ResizeEvent {
    Size size{};
};

using Event =
    std::variant<QuitEvent, FocusEvent, KeyEvent, TextInputEvent, PointerEvent, ResizeEvent>;

/**
 * Result returned by a widget after receiving one semantic event.
 *
 * ignored means that the widget deliberately leaves the event available for further routing.
 * handled stops propagation at that widget. Keeping this result explicit is preferable to a plain
 * bool because call sites remain readable when more routing behavior is added later.
 */
enum class EventResult : std::uint8_t {
    ignored,
    handled,
};

} // namespace sasd::ui
