#pragma once

#include <sasd/ui/geometry.hpp>

#include <cstddef>
#include <cstdint>
#include <string_view>

namespace sasd::ui::terminal {

/**
 * Policy for Unicode characters whose East_Asian_Width property is Ambiguous.
 *
 * Most Western terminal environments render these characters in one cell. Some CJK environments
 * intentionally render them in two. Keeping the choice explicit avoids hiding locale-specific
 * behavior inside the core width algorithm.
 */
enum class AmbiguousWidthMode : std::uint8_t {
    narrow,
    wide,
};

/**
 * One safely decoded UTF-8 scalar value.
 *
 * Invalid input is represented as U+FFFD and consumes exactly one source byte. That recovery rule is
 * deterministic and ensures a caller can always make forward progress without reading beyond the
 * supplied string.
 */
struct DecodedCodePoint {
    char32_t value{U'\uFFFD'};
    std::size_t consumed{0};
    bool valid{false};
};

/**
 * Result of measuring UTF-8 text using the terminal cell-width policy.
 *
 * columns is the widest logical line; rows starts at one even for an empty string. The diagnostic
 * flags matter because cell width alone is not sufficient for all Unicode: zero-width marks and
 * controls require a richer grapheme/control layer before the current ScreenBuffer can render them
 * faithfully.
 */
struct TextMeasurement {
    Coordinate columns{0};
    Coordinate rows{1};
    bool had_invalid_utf8{false};
    bool contains_zero_width{false};
    bool contains_nonprinting_control{false};
    bool saturated{false};

    /**
     * Returns whether the current simple Cell model can render the measured text without silently
     * dropping zero-width marks or terminal control semantics.
     *
     * Invalid UTF-8 is allowed because it has a defined visible replacement representation (U+FFFD).
     */
    [[nodiscard]] bool simpleCellRenderable() const noexcept {
        return !contains_zero_width && !contains_nonprinting_control;
    }
};

/**
 * Versioned terminal Unicode width/UTF-8 helper.
 *
 * The width tables are currently pinned to Unicode 17.0.0 data generated by python-wcwidth 0.7.0.
 * Unicode 18.0 was released only after those upstream generated tables; exposing the pinned version
 * makes that lag explicit rather than pretending that width behavior is timeless.
 *
 * UAX #11 itself notes that East Asian Width needs terminal-specific tailoring. This class therefore
 * implements a practical fixed-cell policy (zero/narrow/wide plus configurable ambiguous width), not
 * a claim that Unicode code-point width alone solves grapheme rendering.
 */
class TextMetrics final {
public:
    TextMetrics() = delete;

    [[nodiscard]] static constexpr std::string_view unicodeTableVersion() noexcept {
        return "17.0.0";
    }

    /**
     * Decodes one UTF-8 scalar beginning at offset.
     *
     * @returns consumed == 0 when offset is at/past the end; otherwise consumed is at least one.
     */
    [[nodiscard]] static DecodedCodePoint decodeOne(std::string_view text,
                                                    std::size_t offset) noexcept;

    /**
     * Returns terminal cell width for one Unicode scalar.
     *
     * Return values follow wcwidth-style semantics:
     * - -1: control/invalid scalar with no ordinary printable width;
     * -  0: zero-width/non-spacing/format value;
     * -  1: normal narrow value;
     * -  2: wide/fullwidth value.
     *
     * Newline handling is a text-layout concern and is performed by measureUtf8()/the renderer before
     * calling this function.
     */
    [[nodiscard]] static int codePointWidth(
        char32_t value,
        AmbiguousWidthMode ambiguous_width = AmbiguousWidthMode::narrow) noexcept;

    /** Measures UTF-8 text without wrapping. CR is ignored and LF starts a new logical row. */
    [[nodiscard]] static TextMeasurement measureUtf8(
        std::string_view text,
        AmbiguousWidthMode ambiguous_width = AmbiguousWidthMode::narrow) noexcept;
};

} // namespace sasd::ui::terminal
